import { useEffect, useState } from "react";
import Navbar from "../components/navbar";
import About from "../components/about";
import Mapbox from "../components/mapbox";
import Toggle from "../components/toggle";
import Janskapsalonsmall from "../components/janskapsalonsmall";
import Janskapsalonflat from "../components/janskapsalonflat";
import { Github, Discord, Whatsapp, Mail } from "../components/socials";
import Skills from "../components/skills";
import Timeline2 from "../components/timeline2";
import Flyn from "../components/flynImg";

export default function Home() {
  const [mode, setMode] = useState("dark");
  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.add(mode);
  }, []);

  return (
    <div className="min-h-screen overflow-visible bg-gray-200 transition-all duration-300 ease-in dark:bg-[#1F295B] ">
      <Navbar />
      <div className=" mx-auto grid w-full max-w-[320px] grid-cols-1 gap-4 px-4 pt-3 pb-6 [grid-auto-rows:265px] [grid-auto-columns:265px] sm:max-w-[640px] sm:grid-cols-2 xl:max-w-[1200px] xl:grid-cols-4 xl:grid-rows-[265px,265px,265px,265px] xl:px-0 ">
        <About />
        <Mapbox colorTheme={mode} />
        <Toggle mode={mode} setMode={setMode} />
        <Janskapsalonsmall />
        <Github />
        <Skills />
        {/* <Timeline /> */}
        <Timeline2 />
        <Discord />
        <Whatsapp />
        <Flyn />
        <Janskapsalonflat />
        <Mail />
      </div>
    </div>
  );
}

// const Home: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Create T3 App</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
//         <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//           <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
//             Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
//           </h1>
//           <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/usage/first-steps"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">First Steps →</h3>
//               <div className="text-lg">
//                 Just the basics - Everything you need to know to set up your
//                 database and authentication.
//               </div>
//             </Link>
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/introduction"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">Documentation →</h3>
//               <div className="text-lg">
//                 Learn more about Create T3 App, the libraries it uses, and how
//                 to deploy it.
//               </div>
//             </Link>
//           </div>
//         </div>
//       </main>
//     </>
//   );
// };
